# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 貓謎工坊
subtitle: Code · Thinking · ACG
description: Code · Thinking · ACG
keywords: 程式,教學,程式教學,BLOG,心得,smile,smilin,BackEnd,後端,後端開發,hexo,微笑,貓謎工坊,NekonazoAtelier,nekonazo,Atelier
author: Smilin
language: zh-TW
timezone:

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://smilin.net/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## https://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## theme: fluid
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/Mr-Smilin/Mr-Smilin.github.io.git
  branch: main #目前最新的預設 branch 是 main，若原本的 branch 為 master，則輸入 master

# 棄用
# feed:
#   type: atom # RSS的类型(atom/rss2)
#   path: atom.xml # 文件路径,默认是atom.xml/rss2.xml
#   limit: 20 # 展示文章的数量,使用0或则false代表展示全部
#   hub:
#   content: # 在RSS文件中是否包含内容 ,有3个值 true/false默认不填为false
#   content_limit: # 指定内容的长度作为摘要,仅仅在上面content设置为false和没有自定义的描述出现
#   content_limit_delim: " " # 上面截取描述的分隔符,截取内容是以指定的这个分隔符作为截取结束的标志.在达到规定的内容长度之前最后出现的这个分隔符之前的内容,，防止从中间截断.

feed:
  limit: 20
  order_by: "-date"
  tag_dir: "tag"
  category_dir: "category"
  rss:
    enable: true
    template: "themes/layout/template/rss.ejs"
    output: "rss.xml"
  atom:
    enable: true
    template: "themes/layout/template/atom.ejs"
    output: "atom.xml"
  jsonFeed:
    enable: true
    template: "themes/layout/template/json.ejs"
    output: "feed.json"
